[package]
name = "bookmarker"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"]}
serde_json = "1"
clap = { version = "4", features = ["derive"] }
terminal_size = "0.3"
dirs = "5.0"

[profile.release]
opt-level = "z"
strip = "symbols"
lto = true
codegen-units = 1
